repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.8
        args: [--config, pyproject.toml]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        language_version: python3.8
        types: [python]
        args: [--rcfile, pyproject.toml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.902
    hooks:
      - id: mypy
        language_version: python3.8
        exclude: ^tests/
        args: [--config, pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.8
        name: isort (python)
        args: [--settings-path, pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli
